# ZSH config file

# Start custom prompt
eval "$(starship init zsh)"

export XDG_CONFIG_DIR="${HOME}/.config"
export SHELL=$(which zsh)

# Enable vi mode
set -o vi

if [ -f ${XDG_CONFIG_DIR}/shell/variables ]; then
    source ${XDG_CONFIG_DIR}/shell/variables
fi

# Cross shell aliases and export statements
if [ -f ${XDG_CONFIG_DIR}/shell/aliases ]; then
    source ${XDG_CONFIG_DIR}/shell/aliases
fi

# Enable better globbing
setopt extendedglob

# Good completions
if [ -f "${XDG_CONFIG_DIR}/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
    . "${XDG_CONFIG_DIR}/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

# Add rust tools to path
if [ -f ~/.cargo/env ]; then
    . ~/.cargo/env
fi

autoload -Uz compinit
compinit
