vim.o.showmatch=true
vim.o.ignorecase=true
vim.o.expandtab=true
vim.o.tabstop=4
vim.o.shiftwidth=4
vim.o.softtabstop=4
vim.o.autoindent=true
vim.o.number=true
vim.o.relativenumber=true
vim.o.noswapfile=true
vim.o.splitbelow=true
vim.o.splitright=true
vim.g.mapleader=' '
