# Bash specific configuration
export XDG_CONFIG_DIR="${HOME}/.config"

# Import shell utilities
if [ ${XDG_CONFIG_DIR}/shell/utils ]; then
    source ${XDG_CONFIG_DIR}/shell/utils
fi

# History related settings
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

# Resize window if needed
shopt -s checkwinsize

# Enable vi mode
set -o vi

# Cross shell aliases and export statements
if [ ${XDG_CONFIG_DIR}/shell/variables ]; then
    source ${XDG_CONFIG_DIR}/shell/variables
fi

if [ ${XDG_CONFIG_DIR}/shell/aliases ]; then
    source ${XDG_CONFIG_DIR}/shell/aliases
fi

# Enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
    if [ -f ${XDG_CONFIG_DIR}/tmux/tmux-complete ]; then
        . ${XDG_CONFIG_DIR}/tmux/tmux-complete
    fi
fi

# Start custom prompt
if [ $(if_installed starship) -ne 1 ]; then
    eval "$(starship init bash)"
fi
